// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXI2zLlahDdguIXaxtzw1vwn3a10Dj5dA',
    appId: '1:709774881962:web:81cc1b3d62a8c05f56ccd3',
    messagingSenderId: '709774881962',
    projectId: 'task-fdf9c',
    authDomain: 'task-fdf9c.firebaseapp.com',
    storageBucket: 'task-fdf9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQHpzG7dk2u-lhyShbnoDiwb9IeUuq44',
    appId: '1:709774881962:android:357c367b7ea428fd56ccd3',
    messagingSenderId: '709774881962',
    projectId: 'task-fdf9c',
    storageBucket: 'task-fdf9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxer_2sBWwN7tq5Eeaag6Lh9gv0nhJFj0',
    appId: '1:709774881962:ios:ed4c3389b5d8816056ccd3',
    messagingSenderId: '709774881962',
    projectId: 'task-fdf9c',
    storageBucket: 'task-fdf9c.firebasestorage.app',
    iosBundleId: 'com.example.assessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxer_2sBWwN7tq5Eeaag6Lh9gv0nhJFj0',
    appId: '1:709774881962:ios:ed4c3389b5d8816056ccd3',
    messagingSenderId: '709774881962',
    projectId: 'task-fdf9c',
    storageBucket: 'task-fdf9c.firebasestorage.app',
    iosBundleId: 'com.example.assessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXI2zLlahDdguIXaxtzw1vwn3a10Dj5dA',
    appId: '1:709774881962:web:563f3af6bb50a14056ccd3',
    messagingSenderId: '709774881962',
    projectId: 'task-fdf9c',
    authDomain: 'task-fdf9c.firebaseapp.com',
    storageBucket: 'task-fdf9c.firebasestorage.app',
  );
}
